#!/usr/bin/env bash
# 534654
FILENAME="/etc/passwd"

while IFC=$(read -r)
do
	USERNAME=$(cut -d':' -f1 "$IFC")
	GROUP_ID=$(cut -d':' -f4 "$IFC" | rev | cut -d':' -f1 | rev)
	COMMAND_SHELL=$(rev "$IFC" | cut -d':' -f1 | rev)
	HOME_DIRECTORY=$(cut -d':' -f6 "$IFC" | rev | cut -d':' -f1 | rev)
	USER_ID=$(cut -d':' -f3 "$IFC" | rev | cut -d':' -f1 | rev)
	PASSWORD=$(cut -d':' -f2 "$IFC" | rev | cut -d':' -f1 | rev)
	User_ID_Info=$(cut -d':' -f5 "$IFC" | rev | cut -d':' -f1 | rev)

	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID place is protected by the passcode $PASSWORD, more info about the user here: $User_ID_Info"
done < $FILENAME
