#!/usr/bin/env bash
# 534654
FILENAME="/etc/passwd"

while IFC=$(read -r)
do

	echo "The user  is part of the  gang, lives in  and rides .  place is protected by the passcode , more info about the user here: "
done < $FILENAME
