#!/usr/bin/env bash
#565468546
a=(ls)
word="-"
arr=()
for i in $a
do
	for sym in $i
	do
		if [ "$sym" == "-" ]
		then
			sed '1d' "$word"
		fi
		word="$word$sym"
	done
	arr+=( "$word" )
done
echo "{$arr[@]}"
